name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag clinic:latest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Start services
      run: docker compose up -d --build

    - name: Run migrations
      run: docker compose run -e DB_PORT=54321 --rm clinic alembic upgrade head

    - name: Run lint
      run: docker compose run --rm clinic flake8

    - name: Run tests
      run: docker compose run --rm clinic pytest